# Generated by Django 4.1.3 on 2023-01-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0002_usuario_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
