# Generated by Django 4.1.3 on 2023-01-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0004_alter_post_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(verbose_name='Contenido'),
        ),
    ]
