# Generated by Django 4.1.3 on 2023-01-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0006_alter_post_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Publicado/No Publicado'),
        ),
    ]
