# Generated by Django 4.1.3 on 2023-01-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0009_rename_bajada_post_subtitulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
