# Generated by Django 4.1.3 on 2023-01-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0011_alter_categoria_options_categoria_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='profesion',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='Usuario', on_delete=django.db.models.deletion.CASCADE, related_name='get_posts', to='Appcoder.usuario', verbose_name='Autor'),
        ),
    ]
