# Generated by Django 4.1.3 on 2023-01-27 13:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0013_remove_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='estado',
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(default='sin user', on_delete=django.db.models.deletion.CASCADE, related_name='get_posts', to='Appcoder.usuario', verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(default='refrigeracion integral', on_delete=django.db.models.deletion.CASCADE, related_name='get_posts', to='Appcoder.categoria', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='post',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='post',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitulo',
            field=models.TextField(verbose_name='Bajada'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Título'),
        ),
    ]
