# Generated by Django 4.1.3 on 2023-02-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0015_alter_post_options_remove_post_autor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
